tradegroupPath = ["/html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[3]/div[2]/div[", "]/div[1]/span"]
tradesPath = ["/html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[3]/div[2]/div[","]/div[2]"]
tradeNamePath = ["/html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[3]/div[2]/div[" , "]/div[1]/div[2]/span" , "]/div[2]/div["]
buyOrderWindowPath = ["/html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[3]/div[2]/div[" , "]/div[2]/div[1]/div/i", "]/div[2]/div["]
orderwindow = ["/html/body/div[2]/div/div/div/div/div[2]/div[2]/div"]
orderwindow_title = ["/html/body/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]"]
delta = ["/html/body/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div[1]/div[2]"]